"""Run the tracking-native style fingerprint v1 (Plan B-4) across the processed ManU matches.

Computes, per team-match: the phase profile, the counter-press table, and the sliced-Wasserstein
frame-embedding stack; then the 6x6 prototype-Wasserstein distance matrix over the six team-match
sides and writes ``results/style_fingerprint_v1.md``.

Run:
    python tools/run_style_fingerprint.py --match all
    python tools/run_style_fingerprint.py --match brighton_manutd
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core import registry  # noqa: E402
from fingerprint import style_fingerprint as sf  # noqa: E402

# southampton_manutd is processed (aligned + ball + goals) but its colour/team anchor collapsed:
# 149084 team-0 player rows vs 670 team-1 (balance 0.004) -- ~all players fell into one team, so it
# yields only one (meaningless, 22-player-blob) side. It is excluded from the two-team analytics;
# re-anchoring is a generator (team_anchor) fix, out of scope for this analytics pass.
EXCLUDED = {"southampton_manutd": "team-anchor collapse (0.004 balance) -> one usable side"}
MATCHES = ["brighton_manutd", "manutd_liverpool", "manutd_fulham", "palace_manutd",
           "manutd_tottenham"]
SHORT = {"brighton_manutd": "Bri", "manutd_liverpool": "Liv", "manutd_fulham": "Ful",
         "palace_manutd": "Pal", "southampton_manutd": "Sou", "manutd_tottenham": "Tot"}
MANU = "Man Utd"


def side_labels(match) -> dict[int, str]:
    """``team_index -> side label``; ManU tagged with the opponent, opponent by its own name.

    ManU is the anchored team 0 in the four home fixtures but team 1 at Palace and Southampton, so the
    ManU index is resolved from ``match.teams`` rather than assumed.
    """
    mi = match.teams.index(MANU)
    return {mi: f"ManU_v{SHORT[match.id]}", 1 - mi: match.teams[1 - mi]}


def _fmt(df: pd.DataFrame, ndp: int = 3) -> str:
    return df.round(ndp).to_string(index=False)


def build(match_ids: list[str]) -> dict:
    """Compute phase profiles, counter-press tables, and embedding sides for the given matches."""
    phase_rows, cp_rows, sides = [], [], {}
    for mid in match_ids:
        m = registry.get(mid)
        labels = side_labels(m)
        pp = sf.phase_profile(m)
        pp.insert(0, "side", pp["team"].map(labels))
        phase_rows.append(pp.drop(columns="team"))
        cp = sf.counterpress(m)
        cp.insert(0, "side", cp["team"].map(labels))
        cp_rows.append(cp.drop(columns="team"))
        for center in (False, True):
            emb = sf.match_embeddings(m, center=center)
            for t, mat in emb.items():
                sides.setdefault(center, {})[labels[t]] = mat
        print(f"[{mid}] phases={len(pp)} rows, counter-press sides={len(cp)}, "
              f"frames={ {labels[t]: len(v) for t, v in emb.items()} }")
    return {
        "phase": pd.concat(phase_rows, ignore_index=True),
        "cp": pd.concat(cp_rows, ignore_index=True),
        "dist": {c: sf.distance_matrix(sides[c]) for c in sides},
    }


def identity_signals(dist: pd.DataFrame) -> dict:
    """Intra-ManU vs ManU-to-opponent mean distance + each ManU side's nearest neighbour."""
    manu = [s for s in dist.index if s.startswith("ManU")]
    opp = [s for s in dist.index if not s.startswith("ManU")]
    intra = [dist.loc[a, b] for i, a in enumerate(manu) for b in manu[i + 1:]]
    cross = [dist.loc[a, b] for a in manu for b in opp]
    nn = {a: dist.loc[a].drop(a).idxmin() for a in dist.index}
    return {"intra_manu": float(np.mean(intra)), "manu_to_opp": float(np.mean(cross)),
            "nearest": nn}


def write_report(res: dict, out: Path) -> None:
    """Render the markdown deliverable (phase profiles, counter-press, 6x6 matrices, honest read)."""
    dist_abs, dist_ctr = res["dist"][False], res["dist"][True]
    sig = identity_signals(dist_abs)
    sig_c = identity_signals(dist_ctr)
    n_sides = len(dist_abs)
    lines = [
        "# Style fingerprint v2 (Plan B-4) - tracking-native, 6-match corpus", "",
        "Three deterministic primitives over player positions + the proximity possession proxy, run",
        "on the processed Man Utd matches. No learned model, no pass stream. Generated by",
        "`tools/run_style_fingerprint.py`; engine `fingerprint/style_fingerprint.py`. v1 (n=3) is",
        "kept alongside at `results/style_fingerprint_v1.md`.", "",
        "**Corpus: 5 of the 6 processed matches.** `southampton_manutd` is excluded -- its team anchor",
        "collapsed (149084 team-0 vs 670 team-1 player rows, balance 0.004), leaving one meaningless",
        "22-player-blob side; it needs re-anchoring in the generator before it can enter two-team",
        "analytics. The five here (brighton, liverpool, fulham, palace, tottenham) are balanced",
        "0.92-1.00. 10 team-match sides.", "",
        f"Config: SW_K={sf.SW_K} directions, SW_Q={sf.SW_Q} quantiles, "
        f"{sf.N_PROTOTYPES} k-means prototypes/side, transition window {sf.TRANSITION_S:.0f}s, "
        f"pressure radius {sf.PRESS_RADIUS_M:.2f}m.", "",
        "## 1. Phase profile (block height, width, compactness, centroid depth; metres)", "",
        "Phases from the Viterbi possession track: `trans_pos`/`trans_neg` within 5s of a flip,",
        "else `in_poss`/`out_poss`. `def_line_height`=deepest-line attacking-x (0=own goal),",
        "`buildup_height`=mean outfield attacking-x. Partial-broadcast view inflates the visible line.",
        "", "```", _fmt(res["phase"], 1), "```", "",
        "## 2. Counter-press (StatsBomb defs: pressure <=4.57m of carrier within 5s of loss)", "",
        "Only balls lost **outside the losing team's own third** are counted. `poss_frames`/`turnovers`",
        "are the ball-gap honesty counters (possession is only defined where the ball links, so most",
        "of the match is unobserved - these are the evaluable base, not full-match totals).",
        "", "```", _fmt(res["cp"]), "```", "",
        f"## 3. OT sliced-Wasserstein distance matrix ({n_sides}x{n_sides} team-match sides)", "",
        "Per side: frame embeddings -> k-means prototypes -> Wasserstein (EMD) between prototype",
        "distributions. Lower = more similar shape distribution. n is tiny; read the matrix, no",
        "significance claims.", "",
        "### 3a. Attack-normalised, absolute field position (territory + shape)", "",
        "```", _fmt(dist_abs), "```",
        f"\nMean intra-ManU distance {sig['intra_manu']:.3f} vs mean ManU-to-opponent "
        f"{sig['manu_to_opp']:.3f}.", "",
        "Nearest neighbour per side:", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig["nearest"].items()),
        "```", "",
        "### 3b. Centred variant (shape only, centroid removed)", "",
        "```", _fmt(dist_ctr), "```",
        f"\nMean intra-ManU {sig_c['intra_manu']:.3f} vs ManU-to-opponent "
        f"{sig_c['manu_to_opp']:.3f}.", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig_c["nearest"].items()),
        "```", "",
        "## Honest read (10 lines)", "",
        READ, "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n-> {out}")
    print(f"identity: intra-ManU {sig['intra_manu']:.3f} vs cross {sig['manu_to_opp']:.3f} "
          f"(abs); {sig_c['intra_manu']:.3f} vs {sig_c['manu_to_opp']:.3f} (centred)")


# Filled from the computed run (see values in section 3 / the tables); kept as a constant so the
# report is reproducible from one command.
READ = """\
1. Identity at n=6 (5 usable): WEAKER than n=3, no longer a clean split. In the territory+shape
   embedding (3a) 4 of 5 ManU sides still find another ManU side nearest (vBri->vLiv, vLiv->vFul,
   vFul->vLiv, vTot->vLiv), and mean intra-ManU 4.73 stays below ManU-to-opponent 5.47 - but that
   gap has roughly halved from n=3 (was 4.36 vs 6.38). The tidy "every ManU side nearest another
   ManU side" claim from v1 does not survive the extra matches.
2. The break is the Palace 0-0: ManU_vPal's nearest neighbour is Crystal Palace (4.023 - the
   smallest distance in the whole matrix), i.e. the two sides of that low-event draw mirror each
   other's territory more than ManU-vPal resembles other ManU games. Opponents no longer
   self-cluster cleanly either (Palace and Tottenham both sit nearest a ManU side).
3. Still territorial, NOT a shape fingerprint - and the extra matches do not change this. Remove the
   centroid (3b) and the separation is essentially gone (intra 1.558 vs cross 1.684) with mixed
   ManU/opponent nearest neighbours. What repeats is WHERE ManU occupy the pitch; n=6 surfaces no
   formation-shape signal.
4. The one trait that survives cleanly: in possession ManU's line/centroid sits higher than its own
   defending block in every match, build-up in the 52-58 m band in_poss across all five - a
   consistent get-up-the-pitch-in-possession habit.
5. Counter-press is NOT the stable 0.60-0.72 habit v1 read: match-level fraction now spans 0.48-0.75
   (ManU_vTot 0.479 / regain 0.250 falls below the old floor; ManU_vPal 0.750 above it). The two 0-3
   losses carry the two lowest 5s-regain of the five (Liverpool 0.347, Tottenham 0.250) - a weak,
   unrewarded press in the heavy defeats, but read it match-level, not as a fixed signature.
6. Palace 0-0 texture: ManU pressed hardest of all here (0.750) while Palace barely counter-pressed
   (0.314, regain 0.086) and lost the ball outside their third fewest of any side (35) - a low-event
   grind where ManU carried the press and Palace sat off.
7. Liverpool 0-3 distortion (still true at n=6): the win-it-and-go attacking transition ran shallow
   vs Liverpool (trans_pos build-up 48.9 m vs 60.8 Brighton / 56.9 Fulham) and ManU sat lower and
   narrower in possession - beaten in the win-it/lose-it phase, not out-shaped.
8. Scope: southampton_manutd is excluded - its team anchor collapsed (149084 team-0 vs 670 team-1
   player rows, balance 0.004), leaving one meaningless 22-player-blob side. The corpus here is 5
   matches, so the win column is Fulham alone. Re-anchoring is a generator fix.
9. Ceilings unchanged: possession + counter-press rest on 1.6-2.7k proximity-possession samples and
   35-102 outside-third losses per side (ball-gap), and the partial broadcast view inflates absolute
   line heights ~+11m: compare across matches, not to FIFA numbers.
10. Verdict at n=6: a territorial ManU signature is still visible but weaker and no longer clean
    (4/5, intra-cross gap halved, Palace breaks to its own opponent); no shape fingerprint emerges;
    and the "stable mid/high press" habit loosens, with the two 0-3 losses lowest on regain.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--match", default="all", help="'all' or a single match id")
    ap.add_argument("--out", default="results/style_fingerprint_v1.md")
    args = ap.parse_args()
    ids = MATCHES if args.match == "all" else [args.match]
    res = build(ids)
    write_report(res, Path(args.out))


if __name__ == "__main__":
    main()
