"""Run the tracking-native style fingerprint v1 (Plan B-4) across the processed ManU matches.

Computes, per team-match: the phase profile, the counter-press table, and the sliced-Wasserstein
frame-embedding stack; then the 6x6 prototype-Wasserstein distance matrix over the six team-match
sides and writes ``results/style_fingerprint_v1.md``.

Run:
    python tools/run_style_fingerprint.py --match all
    python tools/run_style_fingerprint.py --match brighton_manutd
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core import registry  # noqa: E402
from fingerprint import style_fingerprint as sf  # noqa: E402

MATCHES = ["brighton_manutd", "manutd_liverpool", "manutd_fulham"]
SHORT = {"brighton_manutd": "Bri", "manutd_liverpool": "Liv", "manutd_fulham": "Ful"}


def side_labels(match) -> dict[int, str]:
    """``team_index -> side label``; ManU (team 0) tagged with the opponent, opponent by its own name."""
    opp = SHORT[match.id]
    return {0: f"ManU_v{opp}", 1: match.teams[1]}


def _fmt(df: pd.DataFrame, ndp: int = 3) -> str:
    return df.round(ndp).to_string(index=False)


def build(match_ids: list[str]) -> dict:
    """Compute phase profiles, counter-press tables, and embedding sides for the given matches."""
    phase_rows, cp_rows, sides = [], [], {}
    for mid in match_ids:
        m = registry.get(mid)
        labels = side_labels(m)
        pp = sf.phase_profile(m)
        pp.insert(0, "side", pp["team"].map(labels))
        phase_rows.append(pp.drop(columns="team"))
        cp = sf.counterpress(m)
        cp.insert(0, "side", cp["team"].map(labels))
        cp_rows.append(cp.drop(columns="team"))
        for center in (False, True):
            emb = sf.match_embeddings(m, center=center)
            for t, mat in emb.items():
                sides.setdefault(center, {})[labels[t]] = mat
        print(f"[{mid}] phases={len(pp)} rows, counter-press sides={len(cp)}, "
              f"frames={ {labels[t]: len(v) for t, v in emb.items()} }")
    return {
        "phase": pd.concat(phase_rows, ignore_index=True),
        "cp": pd.concat(cp_rows, ignore_index=True),
        "dist": {c: sf.distance_matrix(sides[c]) for c in sides},
    }


def identity_signals(dist: pd.DataFrame) -> dict:
    """Intra-ManU vs ManU-to-opponent mean distance + each ManU side's nearest neighbour."""
    manu = [s for s in dist.index if s.startswith("ManU")]
    opp = [s for s in dist.index if not s.startswith("ManU")]
    intra = [dist.loc[a, b] for i, a in enumerate(manu) for b in manu[i + 1:]]
    cross = [dist.loc[a, b] for a in manu for b in opp]
    nn = {a: dist.loc[a].drop(a).idxmin() for a in dist.index}
    return {"intra_manu": float(np.mean(intra)), "manu_to_opp": float(np.mean(cross)),
            "nearest": nn}


def write_report(res: dict, out: Path) -> None:
    """Render the markdown deliverable (phase profiles, counter-press, 6x6 matrices, honest read)."""
    dist_abs, dist_ctr = res["dist"][False], res["dist"][True]
    sig = identity_signals(dist_abs)
    sig_c = identity_signals(dist_ctr)
    lines = [
        "# Style fingerprint v1 (Plan B-4) - tracking-native", "",
        "Three deterministic primitives over player positions + the proximity possession proxy, run",
        "on all three processed ManU matches. No learned model, no pass stream. Generated by",
        "`tools/run_style_fingerprint.py`; engine `fingerprint/style_fingerprint.py`.", "",
        f"Config: SW_K={sf.SW_K} directions, SW_Q={sf.SW_Q} quantiles, "
        f"{sf.N_PROTOTYPES} k-means prototypes/side, transition window {sf.TRANSITION_S:.0f}s, "
        f"pressure radius {sf.PRESS_RADIUS_M:.2f}m.", "",
        "## 1. Phase profile (block height, width, compactness, centroid depth; metres)", "",
        "Phases from the Viterbi possession track: `trans_pos`/`trans_neg` within 5s of a flip,",
        "else `in_poss`/`out_poss`. `def_line_height`=deepest-line attacking-x (0=own goal),",
        "`buildup_height`=mean outfield attacking-x. Partial-broadcast view inflates the visible line.",
        "", "```", _fmt(res["phase"], 1), "```", "",
        "## 2. Counter-press (StatsBomb defs: pressure <=4.57m of carrier within 5s of loss)", "",
        "Only balls lost **outside the losing team's own third** are counted. `poss_frames`/`turnovers`",
        "are the ball-gap honesty counters (possession is only defined where the ball links, so most",
        "of the match is unobserved - these are the evaluable base, not full-match totals).",
        "", "```", _fmt(res["cp"]), "```", "",
        "## 3. OT sliced-Wasserstein distance matrix (6x6 team-match sides)", "",
        "Per side: frame embeddings -> k-means prototypes -> Wasserstein (EMD) between prototype",
        "distributions. Lower = more similar shape distribution. n is tiny; read the matrix, no",
        "significance claims.", "",
        "### 3a. Attack-normalised, absolute field position (territory + shape)", "",
        "```", _fmt(dist_abs), "```",
        f"\nMean intra-ManU distance {sig['intra_manu']:.3f} vs mean ManU-to-opponent "
        f"{sig['manu_to_opp']:.3f}.", "",
        "Nearest neighbour per side:", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig["nearest"].items()),
        "```", "",
        "### 3b. Centred variant (shape only, centroid removed)", "",
        "```", _fmt(dist_ctr), "```",
        f"\nMean intra-ManU {sig_c['intra_manu']:.3f} vs ManU-to-opponent "
        f"{sig_c['manu_to_opp']:.3f}.", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig_c["nearest"].items()),
        "```", "",
        "## Honest read (10 lines)", "",
        READ, "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n-> {out}")
    print(f"identity: intra-ManU {sig['intra_manu']:.3f} vs cross {sig['manu_to_opp']:.3f} "
          f"(abs); {sig_c['intra_manu']:.3f} vs {sig_c['manu_to_opp']:.3f} (centred)")


# Filled from the computed run (see values in section 3 / the tables); kept as a constant so the
# report is reproducible from one command.
READ = """\
1. Identity: yes, weakly. In the territory+shape embedding (3a) every ManU side's nearest neighbour
   is another ManU side, and mean intra-ManU distance 4.36 sits well below ManU-to-opponent 6.38 - a
   clean ManU / not-ManU split at n=3 (no significance claim).
2. Confound: the three opponents also self-cluster (each opponent's nearest neighbour is another
   opponent), so part of the split is the home/team-0 role + camera framing, not only "ManU-ness";
   the two cannot be disentangled at n=3.
3. The signature is territorial, not shape-invariant: remove the centroid (3b) and separation nearly
   vanishes (intra 1.51 vs cross 1.64) with opponents' nearest neighbours flipping to ManU sides.
   What repeats is WHERE ManU occupy the pitch, not a formation-shape fingerprint.
4. Repeatable ManU traits: in-possession line/centroid always higher than the defending block, and a
   counter-press fraction 0.60-0.72 with 5s regain 0.35-0.47 across all three - a real mid/high-press
   habit that holds match to match.
5. Liverpool 0-3, main distortion (attacking transition): after winning the ball ManU pushed to
   centroid depth 60.8m (Bri) and 56.9m (Ful) but only 48.9m vs Liverpool; trans_pos deepest-line
   55.7/51.0 -> 43.0m. The win-it-go-forward game ran ~12m shallower against Liverpool.
6. Press went flat: ManU counter-press fraction 0.686/0.722 -> 0.600 and 5s regain 0.392/0.468 ->
   0.347, both its lowest of the three - ManU pressed less and won it back less vs Liverpool.
7. In possession ManU also sat lower (in_poss centroid 52.3m vs 55.1/56.8) and narrower (width 32.4m
   vs 38.6m at Brighton) - squeezed onto less territory.
8. Liverpool's own row: fewest balls lost outside their third (58 vs 71-84) and the lowest 5s regain
   of all six sides (0.241) - they rarely coughed it up in danger and did not need to counter-press;
   control, not chaos.
9. Scope/honesty: possession + counter-press rest on 2.0-2.7k proximity-possession samples and
   58-102 outside-third losses per side (possession is defined on a minority of frames - ball-gap),
   and the partial broadcast view inflates absolute line heights ~+11m: compare across matches, not
   to absolute FIFA numbers.
10. Verdict: a repeatable ManU territorial + pressing signature shows across three matches; the 0-3
    was set apart less by shape than by a blunted attacking transition and a weaker, less-rewarded
    counter-press - ManU were outplayed in the win-it/lose-it phase, not out-shaped.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--match", default="all", help="'all' or a single match id")
    ap.add_argument("--out", default="results/style_fingerprint_v1.md")
    args = ap.parse_args()
    ids = MATCHES if args.match == "all" else [args.match]
    res = build(ids)
    write_report(res, Path(args.out))


if __name__ == "__main__":
    main()
