"""Run the tracking-native style fingerprint v1 (Plan B-4) across the processed ManU matches.

Computes, per team-match: the phase profile, the counter-press table, and the sliced-Wasserstein
frame-embedding stack; then the 6x6 prototype-Wasserstein distance matrix over the six team-match
sides and writes ``results/style_fingerprint_v1.md``.

Run:
    python tools/run_style_fingerprint.py --match all
    python tools/run_style_fingerprint.py --match brighton_manutd
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core import registry  # noqa: E402
from fingerprint import style_fingerprint as sf  # noqa: E402

# southampton_manutd was excluded in v2 (team anchor collapsed, balance 0.004 -> one usable side).
# It has since been re-anchored (balance 0.909: 67532 team-0 vs 61404 team-1 player rows), so it now
# yields two usable sides and enters the corpus. All six processed matches are included at v3.
EXCLUDED: dict[str, str] = {}
MATCHES = ["brighton_manutd", "manutd_liverpool", "manutd_fulham", "palace_manutd",
           "manutd_tottenham", "southampton_manutd"]
SHORT = {"brighton_manutd": "Bri", "manutd_liverpool": "Liv", "manutd_fulham": "Ful",
         "palace_manutd": "Pal", "southampton_manutd": "Sou", "manutd_tottenham": "Tot"}
MANU = "Man Utd"


def side_labels(match) -> dict[int, str]:
    """``team_index -> side label``; ManU tagged with the opponent, opponent by its own name.

    ManU is the anchored team 0 in the four home fixtures but team 1 at Palace and Southampton, so the
    ManU index is resolved from ``match.teams`` rather than assumed.
    """
    mi = match.teams.index(MANU)
    return {mi: f"ManU_v{SHORT[match.id]}", 1 - mi: match.teams[1 - mi]}


def _fmt(df: pd.DataFrame, ndp: int = 3) -> str:
    return df.round(ndp).to_string(index=False)


def build(match_ids: list[str]) -> dict:
    """Compute phase profiles, counter-press tables, and embedding sides for the given matches."""
    phase_rows, cp_rows, sides = [], [], {}
    for mid in match_ids:
        m = registry.get(mid)
        labels = side_labels(m)
        pp = sf.phase_profile(m)
        pp.insert(0, "side", pp["team"].map(labels))
        phase_rows.append(pp.drop(columns="team"))
        cp = sf.counterpress(m)
        cp.insert(0, "side", cp["team"].map(labels))
        cp_rows.append(cp.drop(columns="team"))
        for center in (False, True):
            emb = sf.match_embeddings(m, center=center)
            for t, mat in emb.items():
                sides.setdefault(center, {})[labels[t]] = mat
        print(f"[{mid}] phases={len(pp)} rows, counter-press sides={len(cp)}, "
              f"frames={ {labels[t]: len(v) for t, v in emb.items()} }")
    return {
        "phase": pd.concat(phase_rows, ignore_index=True),
        "cp": pd.concat(cp_rows, ignore_index=True),
        "dist": {c: sf.distance_matrix(sides[c]) for c in sides},
    }


def identity_signals(dist: pd.DataFrame) -> dict:
    """Intra-ManU vs ManU-to-opponent mean distance + each ManU side's nearest neighbour."""
    manu = [s for s in dist.index if s.startswith("ManU")]
    opp = [s for s in dist.index if not s.startswith("ManU")]
    intra = [dist.loc[a, b] for i, a in enumerate(manu) for b in manu[i + 1:]]
    cross = [dist.loc[a, b] for a in manu for b in opp]
    nn = {a: dist.loc[a].drop(a).idxmin() for a in dist.index}
    return {"intra_manu": float(np.mean(intra)), "manu_to_opp": float(np.mean(cross)),
            "nearest": nn}


def write_report(res: dict, out: Path) -> None:
    """Render the markdown deliverable (phase profiles, counter-press, 6x6 matrices, honest read)."""
    dist_abs, dist_ctr = res["dist"][False], res["dist"][True]
    sig = identity_signals(dist_abs)
    sig_c = identity_signals(dist_ctr)
    n_sides = len(dist_abs)
    lines = [
        "# Style fingerprint v3 (Plan B-4) - tracking-native, full 6-match corpus", "",
        "Three deterministic primitives over player positions + the proximity possession proxy, run",
        "on the processed Man Utd matches. No learned model, no pass stream. Generated by",
        "`tools/run_style_fingerprint.py`; engine `fingerprint/style_fingerprint.py`. v1 (n=3) and",
        "v2 (n=5, southampton excluded) are kept alongside at `results/style_fingerprint_v1.md` /",
        "`results/style_fingerprint_v2.md`.", "",
        "**Corpus: all 6 processed matches.** `southampton_manutd` was excluded at v2 (team anchor",
        "collapse, balance 0.004) but has since been re-anchored (balance 0.909: 67532 team-0 vs",
        "61404 team-1 player rows), so it now yields two usable sides and joins the corpus. All six",
        "(brighton, liverpool, fulham, palace, tottenham, southampton) are balanced 0.90-1.00. 12",
        "team-match sides.", "",
        f"Config: SW_K={sf.SW_K} directions, SW_Q={sf.SW_Q} quantiles, "
        f"{sf.N_PROTOTYPES} k-means prototypes/side, transition window {sf.TRANSITION_S:.0f}s, "
        f"pressure radius {sf.PRESS_RADIUS_M:.2f}m.", "",
        "## 1. Phase profile (block height, width, compactness, centroid depth; metres)", "",
        "Phases from the Viterbi possession track: `trans_pos`/`trans_neg` within 5s of a flip,",
        "else `in_poss`/`out_poss`. `def_line_height`=deepest-line attacking-x (0=own goal),",
        "`buildup_height`=mean outfield attacking-x. Partial-broadcast view inflates the visible line.",
        "", "```", _fmt(res["phase"], 1), "```", "",
        "## 2. Counter-press (StatsBomb defs: pressure <=4.57m of carrier within 5s of loss)", "",
        "Only balls lost **outside the losing team's own third** are counted. `poss_frames`/`turnovers`",
        "are the ball-gap honesty counters (possession is only defined where the ball links, so most",
        "of the match is unobserved - these are the evaluable base, not full-match totals).",
        "", "```", _fmt(res["cp"]), "```", "",
        f"## 3. OT sliced-Wasserstein distance matrix ({n_sides}x{n_sides} team-match sides)", "",
        "Per side: frame embeddings -> k-means prototypes -> Wasserstein (EMD) between prototype",
        "distributions. Lower = more similar shape distribution. n is tiny; read the matrix, no",
        "significance claims.", "",
        "### 3a. Attack-normalised, absolute field position (territory + shape)", "",
        "```", _fmt(dist_abs), "```",
        f"\nMean intra-ManU distance {sig['intra_manu']:.3f} vs mean ManU-to-opponent "
        f"{sig['manu_to_opp']:.3f}.", "",
        "Nearest neighbour per side:", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig["nearest"].items()),
        "```", "",
        "### 3b. Centred variant (shape only, centroid removed)", "",
        "```", _fmt(dist_ctr), "```",
        f"\nMean intra-ManU {sig_c['intra_manu']:.3f} vs ManU-to-opponent "
        f"{sig_c['manu_to_opp']:.3f}.", "",
        "```",
        "\n".join(f"  {a:12s} -> {b}" for a, b in sig_c["nearest"].items()),
        "```", "",
        "## Honest read (10 lines)", "",
        READ, "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n-> {out}")
    print(f"identity: intra-ManU {sig['intra_manu']:.3f} vs cross {sig['manu_to_opp']:.3f} "
          f"(abs); {sig_c['intra_manu']:.3f} vs {sig_c['manu_to_opp']:.3f} (centred)")


# Filled from the computed run (see values in section 3 / the tables); kept as a constant so the
# report is reproducible from one command.
READ = """\
1. Identity with southampton in (full n=6): the territorial signal has essentially COLLAPSED. Mean
   intra-ManU distance 5.347 vs ManU-to-opponent 5.435 -- a 0.09 gap, down from 0.74 at n=5 (4.73 vs
   5.47) and 2.0 at n=3 (4.36 vs 6.38). The gap shrinks monotonically as matches are added; at the
   full corpus it is negligible. The tidy "every ManU side nearest another ManU side" verdict of v1
   does not survive.
2. Only 3 of 6 ManU sides now find another ManU side nearest (vLiv->vFul, vFul->vLiv, vTot->vLiv).
   The other three point at OPPONENTS: vBri->Southampton, vPal->Crystal Palace, vSou->Fulham. The
   self-clustering that was 4/5 at n=5 is now a minority.
3. Southampton is WHY the signal drops. In the away 0-3 win Man Utd played an outlier shape: in-
   possession build-up 37.0 m and deepest line 31.7 m -- ~15 m lower than any other ManU side (they
   build up in the 52-58 m band in every other match). So ManU_vSou's nearest neighbour is an opponent
   (Fulham), and it even inverts the one v2 habit: here the in-possession line (37) sat LOWER than the
   out-of-possession line (43), the reverse of the get-up-the-pitch pattern that held in the other
   five. A deep counter-attacking away win looks nothing like the home games.
4. Still NO shape fingerprint (centred). Remove the centroid (3b) and intra 1.582 vs cross 1.679 --
   essentially unchanged from v2 (1.558 vs 1.684) and no separation. What little repeats is territory
   (where they stand), and even that is now marginal; formation shape shows nothing.
5. The "consistent high build-up in possession" trait holds in 5 of 6 (in_poss build-up 52-58 m) but
   NOT in the Southampton away win (37 m). It is a home / positive-game-state habit, not an invariant
   -- Southampton is the counter-example.
6. Counter-press match-level now spans 0.46-0.75 across the six (ManU_vSou 0.460 is a new low, below
   ManU_vTot 0.479; ManU_vPal 0.750 the high). Not a fixed signature -- and crucially the two WINS
   split the range at level state (Fulham high, Southampton low), so match-level press does not track
   result: see `results/WINS_VS_LOSSES.md` for the by-state synthesis.
7. Palace 0-0 texture unchanged: ManU pressed hardest of all (0.750) while Palace barely counter-
   pressed (0.314, regain 0.086) and lost the ball outside their third fewest of any side (35).
8. Liverpool 0-3 distortion unchanged at n=6: the win-it-and-go attacking transition ran shallow vs
   Liverpool (trans_pos build-up 48.9 m vs 60.8 Brighton / 56.9 Fulham) and ManU sat lower and
   narrower in possession -- beaten in the win-it/lose-it phase, not out-shaped.
9. Ceilings unchanged: possession + counter-press rest on 1.6-2.7k proximity-possession samples and
   35-103 outside-third losses per side (ball-gap), and the partial broadcast view inflates absolute
   line heights ~+11m: compare across matches, not to FIFA numbers.
10. Verdict at full n=6: the territorial ManU signature that looked clean at n=3 does NOT survive the
    complete corpus -- intra-vs-cross gap 0.09, only 3/6 self-nearest, and the away win is an outright
    outlier. No shape fingerprint, no stable press. A single-team "style fingerprint" from six
    broadcast matches is dominated by opponent / game-state / territory, not a durable identity.
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--match", default="all", help="'all' or a single match id")
    ap.add_argument("--out", default="results/style_fingerprint_v3.md")
    args = ap.parse_args()
    ids = MATCHES if args.match == "all" else [args.match]
    res = build(ids)
    write_report(res, Path(args.out))


if __name__ == "__main__":
    main()
